<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PlatformTarget>x64</PlatformTarget>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Autodesk.AutoCAD.DatabaseServices"/>
        <Using Include="Autodesk.AutoCAD.EditorInput"/>
        <Using Include="Autodesk.AutoCAD.Geometry"/>
        <Using Include="Autodesk.AutoCAD.Runtime"/>
        <Using Include="System.Math">
            <Static>True</Static>
        </Using>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Condition="'$(LegacyAutoCAD)' == 'true'" />
        <PackageReference Include="AutoCAD.NET" ExcludeAssets="runtime"/>
        <PackageReference Include="AutoCAD.NET.Interop" ExcludeAssets="runtime" Condition="'$(LegacyAutoCAD)' != 'true'"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AutoBIMFusion.Common\AutoBIMFusion.Common.csproj"/>
    </ItemGroup>

</Project>
