<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PlatformTarget>x64</PlatformTarget>
        <Platforms>x64</Platforms>
        <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AutoBIMFusion.Merge\AutoBIMFusion.Merge.csproj" GlobalPropertiesToRemove="Platform"/>
    </ItemGroup>

</Project>
