name: Auto Format Code

on:
  push:
    branches: [ main, master ]

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      EnableWindowsTargeting: "true"
      DisableAutoCADDeployment: "true"
      AutoCADUserPluginsDir: "/tmp/"
      AutoCADAllUsersPluginsDir: "/tmp/"
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Fix Code Style
      run: |
        dotnet format AutoBIMFusion.slnx --verbosity diagnostic || \
        dotnet format src/AutoBIMFusion.Plugin/AutoBIMFusion.Plugin.csproj --verbosity diagnostic

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: автоматическое форматирование кода"
        branch: ${{ github.ref_name }}
